# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 陆奕衡 Lu Yiheng
title: CUHKSZ UG'27
email: 123090391@link.cuhk.edu.cn
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  IS-FIELD
Huggingface_username: IsField

# Additional icon links
additional_links:
- title: Link name
  icon: fab github
  url: https://github.com/IS-FIELD
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi I'm Lu Yiheng, a Music lover, Gym bro, also an Aspiring AI researcher. 
  I'm a 3rd Year undergraduate student at The Chinese University of Hong Kong, Shenzhen, majoring in Electric Engineering. 
  I'm experienced in Deep Learning & Signal Processing, and have a strong interest in the field of Swarm Intelligence, Robotics and Networking.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: NVspeech
        # icon: fab fa-github
        link: https://nvspeech.github.io/
        link_text: '<i class="fa-solid fa-cloud"></i> The first Dataset focusing on Non-verbal Vocalization'
        quote: >
          This is a open source Word-level Annotated Speech Dataset with Non-verbal Vocalization for Human-like Synthesis, which is currently under reviewed by NeurIPS 2025 Datasets and Benchmark Track.
        description: | # this will include new lines to allow paragraphs
          I started this project in January 2025 with colleagues in Amphion & Quwan Technology Joint Laboratory. I'm responsible for making precise timestamps and conduct experimental work.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PaperHelper
        # icon: fas cloud
        link: https://github.com/IS-FIELD/EIE3280Project
        link_text: '<i class="fas fa-cloud"></i> An integrated system for novice academic researchers that combines two complementary components'

        quote: >
          This is the project led by myself on the course EIE3280, we use the latests AI technologies to build a system that can help novice academic researchers to Find-Summarize-Retrieval papers.
        description: | # this will include new lines to allow paragraphs
          In this project, I led my teammates to find the shortcomings of current academic searching engines and the classical RAG system, I proposed the new method and split the work to my teammates. I'm responsible for the backend development, including the model finetuing and integration of MCP, LLM and the Database system.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Amphion
        sub_title: Research Advisor
        caption: October 2024 - Present
        link: https://github.com/open-mmlab/Amphion/tree/main
        link_text: '<i class="fab fa-github"></i>Amphion GitHub Page'
        quote: >
          Amphion is the lab led by Prof. WU Zhizheng, focusing on the research of AI Audio, Music, and Speech Generation.
        description: | # this will include new lines to allow paragraphs
          During this period, I have been working on the NVspeech project, and learnt the latest research in the field of Text-to-Speech & Text-to-Audio. 

  - title: Tech Stack
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Languages: Python, PyTorch, HTML, Bash, VHDL
      - Tools: Linux, Git&GitHub, Docker, Huggingface, Slurm, Vivado, MultiSim
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
